name: Generate Profile Stats

on:
  schedule:
    # - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@v1
        with:
          user: ShivArora-Sykkuno
          theme: dark
          output: assets/streak.svg

      - name: Generate Trophy Stats
        uses: ryand57/github-profile-trophy@v1
        with:
          username: ShivArora-Sykkuno
          theme: dracula
          output: assets/trophies.svg

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/*.svg
          git commit -m "Update profile stats" || exit 0
          git push
